apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-persistent-vlc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi